### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by dufoli** [dufoli/salesforce-inspector-reboot#1]
Roadmap to clarify and create sub ticket:
- [x] sosl support
- [x] export guess for object and externalid
- [ ] unit test in build
- [ ] remove object name from subquery result
- [ ] respect order of column of query instead of object return
- [ ] apex runner for batch and queue
- [ ] log analyzer to troubleshoot org limit .
- [ ] composite API support in import
- [ ] refactor parser with tokenizer/lexer and move it out of component
- [ ] move intelisens over text area with list as regular IDE do
- [ ] update react version and migrate code
- [ ] use dependatbot or mend renovate git bot to keep react and all dependency up to date.
- [ ] migrate to typescript
- [ ] pub sub api ?

**Comment by dufoli** [comment]
https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/178
https://github.com/tprouvot/Salesforce-Inspector-reloaded/pull/185

**Comment by dufoli** [comment]
ergonomy for logs : 
- logs is display under runner
- on each line, button download, analyze, display
- if click on one action switch logs view to detail, analyze and return button for back to logs list
- analyze will create node for each flow, trigger, method, soql execute, ... and LIMITE_USAGE will be consolidated by node until main node. => need to calculate code for each node from stock.
